articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('greeting/', views.greeting, name='greeting'),
    path('hello/<name>/', views.hello, name='hello'),
    path('throw/', views.throw, name='throw'),
    path('catch/', views.catch, name='catch'),
]

firstpjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('pages/', include('pages.urls')),
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'
urlpatterns = [
    path('index/', views.index, name='index'),
]

articles/models.py
from django.db import models

# Create your models here.

pages/models.py
from django.db import models

# Create your models here.

articles/views.py
from email import message
from django.shortcuts import render

def index(request):
    return render(request, 'articles/index.html')

def greeting(request):
    info = {'name' : '민지'}
    context = {'info' : info}
    return render(request, 'articles/greeting.html', context)

def throw(request):
    return render(request, 'articles/throw.html')

def catch(request):
    message = request.GET.get('message')
    context = {'message':message}
    return render(request, 'articles/catch.html', context)

def hello(request, name):
    context = {
        'name' : name
    }
    return render(request, 'articles/hello.html', context)

pages/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'pages/index.html')

templates/articles/catch.html
{% extends 'base.html' %}

{% block content %}
  <h1>Catch</h1>
  <h2>데이터 받음 : {{ message }}</h2>
  <a href="{% url 'articles:throw' %}">다시 던지러</a>
{% endblock content %}

templates/articles/greeting.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <p>안녕하세요 제 이름은 {{ info.name }} 입니다.</p>
</body>
</html>

templates/articles/hello.html
{% extends 'base.html' %}
{% block content %}
  <h1>hello {{ name }}님</h1>
{% endblock content %}

templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>만나서 반가워요!</h1>
  
  <a href="{% url 'articles:throw' %}">throw</a>
{% endblock content %}

templates/articles/throw.html
{% extends 'base.html' %}

{% block content %}
  <h1>Throw</h1>

  <form action="{% url 'articles:catch' %}" method="GET">
    <label for="message">Throw</label>
    <input type="text" id="message" name="message">
    <input type="submit">
  </form>

  <a href="{% url 'articles:index' %}">뒤로</a>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <title>Document</title>
</head>
<body>
  <nav class="navbar bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
    </div>
  </nav>

  {% block content %}
  {% endblock content %}

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>
</html>

templates/pages/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>pages index</h1>
{% endblock content %}